spring:
  application:
    name: ore-management-server
  datasource:
    url: jdbc:mysql://localhost:3306/db_ore_management?useSSL=false&serverTimezone=UTC
    username: root
    password: admin
    driver-class-name: com.mysql.cj.jdbc.Driver
server:
  port: 8080
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
